version: '3.8'

services:
  app:
    build: .
    container_name: pizza_system
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - ORIGIN=http://localhost:3000
    restart: unless-stopped
